apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    author: asrorbek
    last: final
  name: nginx1
  namespace: asrorbek
spec:
  containers:
  - image: nginx
    name: nginx1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
