apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: final-exam-ing
  namespace: asrorbek
spec:
  ingressClassName: nginx
  rules:
  - host: asrorbek.nvrbckdown.uz
    http:
      paths:
      - backend:
          service:
            name: final-exam
            port:
              number: 80
        path: /
        pathType: Prefix
